export type SpecialAbilityKind =
  | "positive"
  | "negative"
  | "elite"
  | "gold";

export type SpecialAbilityCategory =
  | "serve"
  | "attack"
  | "set"
  | "receive"
  | "block"
  | "mental"
  | "team"
  | "physical"
  | "growth"
  | "overall"
  | "decision";

export interface SpecialAbilityDefinition {
  id: string;
  name: string;
  kind: SpecialAbilityKind;
  category: SpecialAbilityCategory;
  description: string;
}

export const SPECIAL_ABILITIES = [
  {
    id: "serve_stable",
    name: "サーブ安定○",
    kind: "positive",
    category: "serve",
    description: "サーブミス率を少し下げる",
  },
  {
    id: "serve_bold",
    name: "強気サーブ",
    kind: "positive",
    category: "serve",
    description: "劣勢時のサーブ威力と崩し率を上げる",
  },
  {
    id: "serve_aim",
    name: "狙い打ちサーブ",
    kind: "positive",
    category: "serve",
    description: "弱いレシーバーを狙う成功率を上げる",
  },
  {
    id: "serve_late_game",
    name: "終盤サーブ○",
    kind: "positive",
    category: "serve",
    description: "セット終盤のサーブ性能を上げる",
  },
  {
    id: "serve_streak",
    name: "連続得点サーブ",
    kind: "positive",
    category: "serve",
    description: "連続サーブ時に崩し率が徐々に上がる",
  },
  {
    id: "float_mastery",
    name: "フローター巧者",
    kind: "positive",
    category: "serve",
    description: "フローター系サーブの変化と安定性を上げる",
  },
  {
    id: "jump_serve_mastery",
    name: "ジャンプサーブ巧者",
    kind: "positive",
    category: "serve",
    description: "ジャンプサーブの威力と成功率を上げる",
  },
  {
    id: "receive_breaker",
    name: "崩し屋",
    kind: "positive",
    category: "serve",
    description: "相手のAパス率を下げやすくする",
  },
  {
    id: "attack_course",
    name: "コース打ち○",
    kind: "positive",
    category: "attack",
    description: "空いたコースを狙う決定率を上げる",
  },
  {
    id: "attack_blockout",
    name: "ブロックアウト○",
    kind: "positive",
    category: "attack",
    description: "ブロックアウト成功率を上げる",
  },
  {
    id: "attack_line",
    name: "ストレート巧者",
    kind: "positive",
    category: "attack",
    description: "ストレート攻撃の決定率を上げる",
  },
  {
    id: "attack_cross",
    name: "クロス巧者",
    kind: "positive",
    category: "attack",
    description: "クロス攻撃の決定率を上げる",
  },
  {
    id: "attack_tip",
    name: "軟打巧者",
    kind: "positive",
    category: "attack",
    description: "フェイントとプッシュの成功率を上げる",
  },
  {
    id: "attack_high_contact",
    name: "高打点",
    kind: "positive",
    category: "attack",
    description: "高い打点でブロックの影響を軽減する",
  },
  {
    id: "attack_quick",
    name: "速攻適性○",
    kind: "positive",
    category: "attack",
    description: "クイック攻撃の成功率を上げる",
  },
  {
    id: "attack_backrow",
    name: "バックアタック○",
    kind: "positive",
    category: "attack",
    description: "後衛攻撃の決定率を上げる",
  },
  {
    id: "attack_out_of_system",
    name: "二段トス打ち○",
    kind: "positive",
    category: "attack",
    description: "崩れたトスでも決定力低下を軽減する",
  },
  {
    id: "attack_transition",
    name: "切り返し○",
    kind: "positive",
    category: "attack",
    description: "ディグ後の切り返し攻撃性能を上げる",
  },
  {
    id: "attack_clutch",
    name: "終盤決定力○",
    kind: "positive",
    category: "attack",
    description: "終盤とデュース時の攻撃成功率を上げる",
  },
  {
    id: "attack_streak",
    name: "連続得点○",
    kind: "positive",
    category: "attack",
    description: "連続得点中に攻撃性能が少し上がる",
  },
  {
    id: "set_stable",
    name: "トス安定○",
    kind: "positive",
    category: "set",
    description: "トス精度の乱れを軽減する",
  },
  {
    id: "set_quick_link",
    name: "クイック連携○",
    kind: "positive",
    category: "set",
    description: "ミドルとの速攻成功率を上げる",
  },
  {
    id: "set_side_link",
    name: "サイド連携○",
    kind: "positive",
    category: "set",
    description: "サイドへのトス品質を上げる",
  },
  {
    id: "set_back",
    name: "バックセット○",
    kind: "positive",
    category: "set",
    description: "バックトスの精度と選択幅を上げる",
  },
  {
    id: "set_second_ball",
    name: "二段トス○",
    kind: "positive",
    category: "set",
    description: "セッター以外の緊急トス品質を上げる",
  },
  {
    id: "set_distribution",
    name: "配球センス○",
    kind: "positive",
    category: "set",
    description: "攻撃先の偏りを抑えてブロックを散らす",
  },
  {
    id: "set_emergency",
    name: "緊急セット○",
    kind: "positive",
    category: "set",
    description: "崩れたレシーブからのトス品質低下を軽減する",
  },
  {
    id: "receive_serve",
    name: "サーブレシーブ○",
    kind: "positive",
    category: "receive",
    description: "サーブレシーブ成功率を上げる",
  },
  {
    id: "receive_dig",
    name: "ディグ○",
    kind: "positive",
    category: "receive",
    description: "強打へのディグ成功率を上げる",
  },
  {
    id: "receive_range",
    name: "守備範囲○",
    kind: "positive",
    category: "receive",
    description: "ボールへの到達率を上げる",
  },
  {
    id: "receive_power",
    name: "強打耐性○",
    kind: "positive",
    category: "receive",
    description: "高威力スパイクへの守備成功率を上げる",
  },
  {
    id: "receive_tip",
    name: "フェイント対応○",
    kind: "positive",
    category: "receive",
    description: "軟打とフェイントへの反応を上げる",
  },
  {
    id: "receive_touch",
    name: "ワンタッチ処理○",
    kind: "positive",
    category: "receive",
    description: "ブロックタッチ後の処理成功率を上げる",
  },
  {
    id: "receive_connect",
    name: "つなぎ○",
    kind: "positive",
    category: "receive",
    description: "苦しい体勢でも次につなぎやすくする",
  },
  {
    id: "receive_cover",
    name: "カバーリング○",
    kind: "positive",
    category: "receive",
    description: "味方攻撃後のカバー成功率を上げる",
  },
  {
    id: "block_read",
    name: "読みブロック○",
    kind: "positive",
    category: "block",
    description: "相手配球を読む成功率を上げる",
  },
  {
    id: "block_commit",
    name: "コミット○",
    kind: "positive",
    category: "block",
    description: "クイックへのコミット成功率を上げる",
  },
  {
    id: "block_side",
    name: "サイドブロック○",
    kind: "positive",
    category: "block",
    description: "サイドへの移動ブロック性能を上げる",
  },
  {
    id: "block_touch",
    name: "ブロックタッチ○",
    kind: "positive",
    category: "block",
    description: "ワンタッチ獲得率を上げる",
  },
  {
    id: "block_close",
    name: "閉じる○",
    kind: "positive",
    category: "block",
    description: "ブロッカー間の隙間を減らす",
  },
  {
    id: "block_team",
    name: "ブロック連携○",
    kind: "positive",
    category: "block",
    description: "複数枚ブロック時の性能を上げる",
  },
  {
    id: "mental_clutch",
    name: "勝負強さ○",
    kind: "positive",
    category: "mental",
    description: "接戦終盤の主要行動成功率を上げる",
  },
  {
    id: "mental_comeback",
    name: "逆境○",
    kind: "positive",
    category: "mental",
    description: "ビハインド時に性能低下しにくくする",
  },
  {
    id: "mental_start",
    name: "立ち上がり○",
    kind: "positive",
    category: "mental",
    description: "セット序盤のミス率を下げる",
  },
  {
    id: "team_mood",
    name: "ムードメーカー",
    kind: "positive",
    category: "team",
    description: "出場時に味方の調子悪化を少し抑える",
  },
  {
    id: "team_captaincy",
    name: "キャプテンシー",
    kind: "positive",
    category: "team",
    description: "劣勢時のチーム精神低下を抑える",
  },
  {
    id: "mental_reset",
    name: "切替上手",
    kind: "positive",
    category: "mental",
    description: "自分のミス後の連続ミス率を下げる",
  },
  {
    id: "mental_focus",
    name: "集中力",
    kind: "positive",
    category: "mental",
    description: "長いラリーや終盤の精度低下を軽減する",
  },
  {
    id: "mental_calm",
    name: "冷静",
    kind: "positive",
    category: "mental",
    description: "相手連続得点時の判断低下を抑える",
  },
  {
    id: "physical_stamina",
    name: "スタミナ○",
    kind: "positive",
    category: "physical",
    description: "試合中の疲労蓄積を軽減する",
  },
  {
    id: "physical_recovery",
    name: "疲労回復○",
    kind: "positive",
    category: "physical",
    description: "週進行時の疲労回復量を上げる",
  },
  {
    id: "physical_injury_resist",
    name: "怪我耐性○",
    kind: "positive",
    category: "physical",
    description: "練習と合宿の怪我率を下げる",
  },
  {
    id: "growth_motivation",
    name: "成長意欲○",
    kind: "positive",
    category: "growth",
    description: "練習成長量が少し上がりやすくなる",
  },
  {
    id: "growth_practice",
    name: "練習上手",
    kind: "positive",
    category: "growth",
    description: "個人練習の成功率とコツ獲得率を上げる",
  },
  {
    id: "mental_tournament",
    name: "大会慣れ",
    kind: "positive",
    category: "mental",
    description: "公式戦で緊張ペナルティを受けにくくする",
  },
  {
    id: "serve_unstable",
    name: "サーブ不安定",
    kind: "negative",
    category: "serve",
    description: "サーブミス率が上がる",
  },
  {
    id: "serve_overhit",
    name: "強打しすぎ",
    kind: "negative",
    category: "serve",
    description: "威力は上がるがサーブミス率も上がる",
  },
  {
    id: "serve_pressure_bad",
    name: "プレッシャーサーブ×",
    kind: "negative",
    category: "serve",
    description: "終盤とデュース時のサーブ精度が落ちる",
  },
  {
    id: "attack_low_finish",
    name: "決定力不足",
    kind: "negative",
    category: "attack",
    description: "高難度場面でスパイク決定率が落ちる",
  },
  {
    id: "attack_block_fear",
    name: "ブロック恐怖症",
    kind: "negative",
    category: "attack",
    description: "強いブロック相手に攻撃性能が落ちる",
  },
  {
    id: "attack_predictable",
    name: "コース単調",
    kind: "negative",
    category: "attack",
    description: "同じ攻撃コースを読まれやすくなる",
  },
  {
    id: "attack_quick_bad",
    name: "速攻苦手",
    kind: "negative",
    category: "attack",
    description: "クイック参加時の成功率が落ちる",
  },
  {
    id: "set_unstable",
    name: "トス乱れ",
    kind: "negative",
    category: "set",
    description: "疲労と劣勢時にトス精度が落ちやすい",
  },
  {
    id: "set_bias",
    name: "配球偏り",
    kind: "negative",
    category: "set",
    description: "特定攻撃手へ偏りブロックに読まれやすい",
  },
  {
    id: "set_emergency_bad",
    name: "緊急トス×",
    kind: "negative",
    category: "set",
    description: "崩れた場面のトス品質が落ちる",
  },
  {
    id: "receive_weak",
    name: "レシーブ苦手",
    kind: "negative",
    category: "receive",
    description: "サーブレシーブ成功率が落ちる",
  },
  {
    id: "receive_power_fear",
    name: "強打恐怖",
    kind: "negative",
    category: "receive",
    description: "高威力攻撃へのディグ成功率が落ちる",
  },
  {
    id: "receive_tip_bad",
    name: "フェイント弱い",
    kind: "negative",
    category: "receive",
    description: "軟打とフェイントへの反応が落ちる",
  },
  {
    id: "receive_cover_slow",
    name: "カバー遅れ",
    kind: "negative",
    category: "receive",
    description: "カバーリング到達率が落ちる",
  },
  {
    id: "block_slow",
    name: "ブロック遅れ",
    kind: "negative",
    category: "block",
    description: "移動ブロックの到達率が落ちる",
  },
  {
    id: "block_tooling",
    name: "吸い込み癖",
    kind: "negative",
    category: "block",
    description: "ブロックアウトと吸い込み失点が増える",
  },
  {
    id: "mental_choke",
    name: "勝負弱さ",
    kind: "negative",
    category: "mental",
    description: "接戦終盤の成功率が落ちる",
  },
  {
    id: "mental_run_bad",
    name: "連続失点癖",
    kind: "negative",
    category: "mental",
    description: "相手連続得点中に性能が落ちやすい",
  },
  {
    id: "physical_tires",
    name: "疲れやすい",
    kind: "negative",
    category: "physical",
    description: "練習と試合の疲労が増えやすい",
  },
  {
    id: "physical_injury_prone",
    name: "怪我しやすい",
    kind: "negative",
    category: "physical",
    description: "練習と合宿の怪我率が上がる",
  },
  {
    id: "elite_serve_craftsman",
    name: "サーブ職人",
    kind: "elite",
    category: "serve",
    description: "サーブ安定と狙い打ちを大きく強化する",
  },
  {
    id: "elite_service_ace",
    name: "サービスエース製造機",
    kind: "elite",
    category: "serve",
    description: "サービスエースと大崩し率を大きく上げる",
  },
  {
    id: "elite_serve_hunter",
    name: "エースキラーサーブ",
    kind: "elite",
    category: "serve",
    description: "相手主力を狙ったサーブ効果を大きく上げる",
  },
  {
    id: "elite_court_hitter",
    name: "コートヒッター",
    kind: "elite",
    category: "attack",
    description: "コース選択精度と打ち分け性能を大きく上げる",
  },
  {
    id: "elite_block_crusher",
    name: "ブロッククラッシャー",
    kind: "elite",
    category: "attack",
    description: "高ブロック相手への決定率低下を軽減する",
  },
  {
    id: "elite_fast_finisher",
    name: "高速決定力",
    kind: "elite",
    category: "attack",
    description: "速いテンポの攻撃決定率を大きく上げる",
  },
  {
    id: "elite_allround_attacker",
    name: "万能アタッカー",
    kind: "elite",
    category: "attack",
    description: "前衛後衛と崩れ球で性能低下しにくくする",
  },
  {
    id: "elite_game_maker",
    name: "ゲームメイカー",
    kind: "elite",
    category: "set",
    description: "トス品質と味方攻撃効率を同時に強化する",
  },
  {
    id: "elite_deception_set",
    name: "幻惑配球",
    kind: "elite",
    category: "set",
    description: "相手ブロックの読み成功率を下げる",
  },
  {
    id: "elite_defense_craftsman",
    name: "守備職人",
    kind: "elite",
    category: "receive",
    description: "レシーブとディグとカバーを総合強化する",
  },
  {
    id: "elite_receive_wall",
    name: "鉄壁レシーブ",
    kind: "elite",
    category: "receive",
    description: "強サーブへのレシーブ安定度を大きく上げる",
  },
  {
    id: "elite_block_commander",
    name: "ブロック司令塔",
    kind: "elite",
    category: "block",
    description: "自分と周囲のブロック連携を強化する",
  },
  {
    id: "elite_shutdown",
    name: "シャットアウト",
    kind: "elite",
    category: "block",
    description: "ブロック得点率を大きく上げる",
  },
  {
    id: "elite_clutch",
    name: "クラッチプレイヤー",
    kind: "elite",
    category: "mental",
    description: "接戦終盤に攻守両面を強化する",
  },
  {
    id: "elite_steel_mental",
    name: "鉄のメンタル",
    kind: "elite",
    category: "mental",
    description: "劣勢と連続失点と大舞台の悪影響を軽減する",
  },
  {
    id: "gold_absolute_ace",
    name: "絶対的エース",
    kind: "gold",
    category: "attack",
    description: "難しい終盤でも決定力を落としにくくする",
  },
  {
    id: "gold_serve_king",
    name: "サーブ王",
    kind: "gold",
    category: "serve",
    description: "威力と精度と崩しと連続得点を最高クラスへ高める",
  },
  {
    id: "gold_commander",
    name: "司令塔",
    kind: "gold",
    category: "set",
    description: "全攻撃手の効率を引き上げ配球を読まれにくくする",
  },
  {
    id: "gold_guardian",
    name: "守護神",
    kind: "gold",
    category: "receive",
    description: "レシーブとディグとカバーを最高クラスへ高める",
  },
  {
    id: "gold_iron_wall",
    name: "鉄壁",
    kind: "gold",
    category: "block",
    description: "ブロック得点とワンタッチと連携を最高クラスへ高める",
  },
  {
    id: "gold_flow_controller",
    name: "流れの支配者",
    kind: "gold",
    category: "team",
    description: "味方の連続得点を伸ばし相手の連続得点を止めやすくする",
  },
  {
    id: "gold_indomitable",
    name: "不屈の闘志",
    kind: "gold",
    category: "mental",
    description: "劣勢と大舞台と終盤で反発力を発揮する",
  },
  {
    id: "gold_total_player",
    name: "万能選手",
    kind: "gold",
    category: "overall",
    description: "複数ポジションと局面で適性低下を大きく軽減する",
  },
  {
    id: "gold_ultra_quick",
    name: "超速攻",
    kind: "gold",
    category: "attack",
    description: "クイックの速度と成功率とブロック回避を最大強化する",
  },
  {
    id: "gold_court_brain",
    name: "コートの頭脳",
    kind: "gold",
    category: "decision",
    description: "配球と守備位置とブロック判断を全体強化する",
  },
] as const satisfies readonly SpecialAbilityDefinition[];

const specialAbilityById = new Map<string, SpecialAbilityDefinition>(
  SPECIAL_ABILITIES.map((ability) => [ability.id, ability]),
);

export function getSpecialAbilityDefinition(
  id: string,
): SpecialAbilityDefinition | undefined {
  return specialAbilityById.get(id);
}

export function getSpecialAbilitiesByKind(
  kind: SpecialAbilityKind,
): readonly SpecialAbilityDefinition[] {
  return SPECIAL_ABILITIES.filter((ability) => ability.kind === kind);
}
