from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
def r(p): return (ROOT/p).read_text(encoding='utf-8')
def w(p,s): q=ROOT/p; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(s,encoding='utf-8')
def repl(p,a,b):
 t=r(p)
 if a not in t: raise SystemExit(f'missing in {p}: {a[:100]}')
 w(p,t.replace(a,b,1))

def tests():
 w('tests/unit/ui/shell/phase12Navigation.test.ts','''import { describe,expect,it } from "vitest";import { APP_NAVIGATION } from "../../../../src/ui/shell/appNavigation";describe("Phase 12 navigation",()=>{it("uses the five approved game tabs",()=>{expect(APP_NAVIGATION.map((item)=>item.label)).toEqual(["ホーム","選手","学校","試合","その他"]);expect(APP_NAVIGATION.some((item)=>item.label==="育成")).toBe(false);});});\n''')
 w('tests/unit/ui/OperationBlockingOverlay.test.tsx','''import { render,screen } from "@testing-library/react";import { describe,expect,it } from "vitest";import { OperationBlockingOverlay } from "../../../src/ui/status/OperationBlockingOverlay";describe("OperationBlockingOverlay",()=>{it("blocks the viewport while an operation is submitting",()=>{render(<OperationBlockingOverlay operation={{status:"submitting",label:"練習設定を保存しています…"}}/>);expect(screen.getByRole("status")).toHaveTextContent("練習設定を保存しています…");expect(screen.getByRole("status")).toHaveAttribute("aria-busy","true");});it("does not block while idle",()=>{render(<OperationBlockingOverlay operation={{status:"idle"}}/>);expect(screen.queryByTestId("operation-blocking-overlay")).toBeNull();});});\n''')

def production():
 w('src/ui/shell/appNavigation.ts','''export type AppTab = "home" | "team" | "school" | "match" | "more";\nexport const APP_NAVIGATION = [\n  { id: "home", label: "ホーム", icon: "home" },\n  { id: "team", label: "選手", icon: "team" },\n  { id: "school", label: "学校", icon: "training" },\n  { id: "match", label: "試合", icon: "match" },\n  { id: "more", label: "その他", icon: "more" },\n] as const;\n''')
 w('src/ui/status/OperationBlockingOverlay.tsx','''import type { OperationState } from "../../app/useGameSession";import "./operation-status.css";export function OperationBlockingOverlay({operation}:{operation:OperationState}){if(operation.status!=="submitting")return null;return <div className="operation-blocking-overlay" data-testid="operation-blocking-overlay"><div aria-busy="true" aria-live="polite" className="operation-blocking-overlay__panel" role="status"><span className="operation-blocking-overlay__spinner" aria-hidden="true"/><strong>{operation.label}</strong><small>処理が完了するまでお待ちください</small></div></div>;}\n''')
 p='src/ui/status/operation-status.css'; t=r(p); t+='''\n.operation-blocking-overlay{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;padding:24px;background:rgba(3,12,24,.68);backdrop-filter:blur(3px);touch-action:none}.operation-blocking-overlay__panel{min-width:min(82vw,320px);display:grid;justify-items:center;gap:10px;padding:24px 20px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:rgba(10,29,52,.96);box-shadow:0 18px 50px rgba(0,0,0,.4);text-align:center;color:#fff}.operation-blocking-overlay__panel small{color:rgba(255,255,255,.68)}.operation-blocking-overlay__spinner{width:38px;height:38px;border:4px solid rgba(255,255,255,.2);border-top-color:#ff9f1c;border-radius:50%;animation:operation-spin .75s linear infinite}@keyframes operation-spin{to{transform:rotate(360deg)}}@media(prefers-reduced-motion:reduce){.operation-blocking-overlay__spinner{animation:none;border-top-color:#ff9f1c}}\n''';w(p,t)
 p='src/ui/shell/GamePageFrame.tsx';t=r(p);t=t.replace('import { GameHeader } from "./GameHeader";','import { GameHeader } from "./GameHeader";\nimport { OperationBlockingOverlay } from "../status/OperationBlockingOverlay";');t=t.replace('      <BottomGameNav activeTab={activeTab} onChange={onChangeTab} />','      <BottomGameNav activeTab={activeTab} onChange={onChangeTab} />\n      <OperationBlockingOverlay operation={operation} />');w(p,t)
 w('src/features/more/MoreScreen.tsx','''import "./more.css";interface MoreScreenProps{accountLabel:string;onOpenShop:()=>void;onSignOut:()=>void;}export function MoreScreen({accountLabel,onOpenShop,onSignOut}:MoreScreenProps){return <main className="app-content more-screen"><section className="more-screen__heading"><p className="section-kicker">管理メニュー</p><h2>その他</h2><p>ショップとアカウント設定をまとめています。</p></section><section className="more-screen__menu" aria-label="その他のメニュー"><button aria-label="ショップ" className="more-screen__item" onClick={onOpenShop} type="button"><span><strong>ショップ</strong><small>アイテムを確認</small></span><span aria-hidden="true">›</span></button></section><section className="more-screen__account" aria-label="アカウント"><div><span>ログイン中</span><strong>{accountLabel}</strong></div><button onClick={onSignOut} type="button">ログアウト</button></section></main>}\n''')
 # School gains scouting as an internal destination.
 p='src/features/school/SchoolScreen.tsx';t=r(p);t=t.replace('  onUpgradeFacility: (key: FacilityKey) => void;','  onUpgradeFacility: (key: FacilityKey) => void;\n  onOpenScouting: () => void;');t=t.replace('type SchoolView = "facilities" | "records" | "alumni";','type SchoolView = "facilities" | "scouting" | "records" | "alumni";');t=t.replace('export function SchoolScreen({ state, onUpgradeFacility }: SchoolScreenProps) {','export function SchoolScreen({ state, onUpgradeFacility, onOpenScouting }: SchoolScreenProps) {');t=t.replace('["facilities", "設備"],\n            ["records", "記録"],','["facilities", "設備"],\n            ["scouting", "スカウト"],\n            ["records", "記録"],');t=t.replace('onClick={() => setView(id)}','onClick={() => (id === "scouting" ? onOpenScouting() : setView(id))}');w(p,t)
 # Player hub: condition faces + training chips + no fatigue.
 w('src/features/team/PlayerHubScreen.tsx','''import { useMemo,useState } from "react";import { isWeeklyActionCompleted } from "../../domain/calendar/weekProgression";import type { PlayerConcernCode,PlayerRole } from "../../domain/dynamics/teamDynamicsTypes";import type { GameState } from "../../domain/model/GameState";import type { Player } from "../../domain/model/Player";import type { TeamSelection } from "../../domain/model/TeamSelection";import type { PlayerId } from "../../domain/model/identifiers";import { getPlayerConditionPresentation } from "../../domain/player/playerCondition";import { calculatePlayerDisplayPower,summarizePlayerAbilities } from "../../domain/selectors/playerPresentation";import { individualTrainingInstructions } from "../../data/individualTrainingInstructions";import { BottomSheet } from "../../ui/BottomSheet";import { StatBar } from "../../ui/theme/StatBar";import { TeamDynamicsPanel } from "./TeamDynamicsPanel";import { TeamScreen } from "./TeamScreen";import "./player-hub.css";
interface PlayerHubScreenProps{state:GameState;selection:TeamSelection;onChange:(selection:TeamSelection)=>void;onAssignLeadership:(captainPlayerId:PlayerId,viceCaptainPlayerId:PlayerId)=>void|Promise<void>;leadershipPending?:boolean;trainingPending?:boolean;onChangeTraining?:(playerId:PlayerId,instructionId:string)=>void|Promise<void>;}type HubMode="roster"|"lineup"|"dynamics";const abilityLabels={attack:"攻撃",defense:"守備",jump:"跳躍",stamina:"スタミナ",mental:"メンタル"} as const;const roleLabels:Record<PlayerRole,string>={ace:"エース",starter:"先発",rotation:"ローテーション",development:"育成枠",reserve:"控え"};const concernLabels:Record<PlayerConcernCode,string>={"playing-time":"出場機会","role-mismatch":"役割への不満","injury-overuse":"怪我・起用負荷","team-slump":"チーム不調"};const playerName=(p:Player)=>`${p.lastName} ${p.firstName}`;const playerOverall=(p:Player)=>Math.round(calculatePlayerDisplayPower(p)/100);
function HubTabs({mode,onChange}:{mode:HubMode;onChange:(m:HubMode)=>void}){return <nav className="player-hub__tabs" aria-label="選手画面の表示切替">{([['roster','選手一覧'],['lineup','編成'],['dynamics','チーム状態']] as const).map(([id,label])=><button aria-current={mode===id?'page':undefined} key={id} onClick={()=>onChange(id)} type="button">{label}</button>)}</nav>}
export function PlayerHubScreen({state,selection,onChange,onAssignLeadership,leadershipPending=false,trainingPending=false,onChangeTraining}:PlayerHubScreenProps){const[mode,setMode]=useState<HubMode>('roster');const[selectedPlayerId,setSelectedPlayerId]=useState<PlayerId|null>(null);const[trainingPlayerId,setTrainingPlayerId]=useState<PlayerId|null>(null);const school=state.schools[state.userSchoolId]!;const players=useMemo(()=>school.playerIds.map(id=>state.players[id]).filter((p):p is Player=>Boolean(p)),[school.playerIds,state.players]);const selectedPlayer=selectedPlayerId?(state.players[selectedPlayerId]??null):null;const trainingPlayer=trainingPlayerId?(state.players[trainingPlayerId]??null):null;const trainingDone=isWeeklyActionCompleted(state,'training');const assignmentName=(id:PlayerId)=>{const assignment=state.weeklySchedule.trainingPlan.individualAssignments.find(a=>a.playerId===id);return individualTrainingInstructions.find(i=>i.id===(assignment?.instructionId??'instruction.overall'))?.name??'全体'};
if(mode==='lineup')return <div className="player-hub"><HubTabs mode={mode} onChange={setMode}/><TeamScreen onChange={onChange} selection={selection} state={state}/></div>;if(mode==='dynamics')return <main className="app-content player-hub"><HubTabs mode={mode} onChange={setMode}/><TeamDynamicsPanel onAssignLeadership={onAssignLeadership} pending={leadershipPending} state={state}/></main>;
if(selectedPlayer){const abilities=summarizePlayerAbilities(selectedPlayer),role=state.teamDynamics.playerRoles[selectedPlayer.id]??'reserve',concerns=state.teamDynamics.playerConcerns[selectedPlayer.id]??[],condition=getPlayerConditionPresentation(selectedPlayer.condition);return <main className="app-content player-hub player-detail"><button aria-label="選手一覧へ戻る" className="player-detail__back" onClick={()=>setSelectedPlayerId(null)} type="button">‹ 選手一覧</button><section className="player-detail__summary"><div className="player-detail__identity"><h2>{playerName(selectedPlayer)}</h2><span>{selectedPlayer.grade}年・{selectedPlayer.preferredPosition}・{selectedPlayer.heightCm}cm</span></div><div className="player-detail__power"><span>総合力</span><strong>{playerOverall(selectedPlayer)}</strong></div></section><section className="player-detail__stats" aria-label="選手能力">{Object.entries(abilities).map(([key,value])=><StatBar key={key} label={abilityLabels[key as keyof typeof abilityLabels]} tone="accent" value={value}/>)}</section><section className="player-detail__metrics" aria-label="選手状態"><article className={`player-condition player-condition--${condition.colorToken}`}><span>調子</span><strong>{condition.icon} {condition.label}</strong></article><article><span>士気</span><strong>{selectedPlayer.morale}</strong></article><article><span>役割</span><strong>{roleLabels[role]}</strong></article><article><span>信頼</span><strong>{selectedPlayer.trust}</strong></article></section>{concerns.length?<section className="player-detail__concerns" aria-label="選手の気になる状態"><h3>気になる状態</h3><ul>{concerns.map((c,i)=><li key={`${c.code}:${i}`}>{concernLabels[c.code]}・重要度 {c.severity}/3</li>)}</ul></section>:null}</main>}
return <main className="app-content player-hub"><HubTabs mode={mode} onChange={setMode}/><section className="player-hub__heading"><div><p className="section-kicker">登録選手</p><h2>選手一覧</h2></div><span>{players.length}人</span></section><div className="player-roster">{players.map((player,index)=>{const condition=getPlayerConditionPresentation(player.condition),training=assignmentName(player.id);return <article className="player-roster__row" data-testid="roster-player-row" key={player.id}><button aria-label={`選手詳細 ${playerName(player)}`} className="player-roster__main" onClick={()=>setSelectedPlayerId(player.id)} type="button"><span className="player-roster__number">{index+1}</span><span className="player-roster__name"><strong>{playerName(player)}</strong><small>{player.grade}年・{player.preferredPosition}・{player.heightCm}cm</small></span><span className={`player-roster__condition player-condition--${condition.colorToken}`} title={condition.label}><b aria-hidden="true">{condition.icon}</b><small>{condition.label}</small></span><span className="player-roster__overall"><small>総合</small><strong>{playerOverall(player)}</strong></span></button><button aria-label={`${playerName(player)} 練習 ${training}`} className="player-training-chip" disabled={trainingPending||trainingDone} onClick={()=>setTrainingPlayerId(player.id)} type="button">{training}</button></article>})}</div><BottomSheet open={Boolean(trainingPlayer)} onClose={()=>setTrainingPlayerId(null)} title={trainingPlayer?`${playerName(trainingPlayer)}の個人練習`:'個人練習'} description="今週の練習を選択"><div className="player-training-options">{individualTrainingInstructions.map(item=><button key={item.id} disabled={trainingPending||trainingDone} onClick={()=>{if(trainingPlayer)void onChangeTraining?.(trainingPlayer.id,item.id);setTrainingPlayerId(null)}} type="button"><strong>{item.name}</strong><small>{item.description}</small></button>)}</div></BottomSheet></main>}
''')
 p='src/features/team/player-hub.css';t=r(p);t+='''\n.player-roster__row{position:relative}.player-roster__main{display:grid;grid-template-columns:28px minmax(0,1fr) 58px 42px 52px;align-items:center;width:100%;min-height:62px;padding:8px 62px 8px 10px;border:0;background:transparent;color:inherit;text-align:left}.player-roster__condition{display:grid;justify-items:center;font-size:17px}.player-roster__condition small{font-size:9px;font-weight:800}.player-training-chip{position:absolute;right:8px;top:50%;transform:translateY(-50%);min-width:48px;padding:7px 7px;border:1px solid rgba(116,216,255,.32);border-radius:10px;background:rgba(31,120,171,.24);color:#eef9ff;font-size:12px;font-weight:900}.player-training-chip:disabled{opacity:.55}.player-condition--red{color:#ff665f}.player-condition--green{color:#65d987}.player-condition--yellow{color:#ffd35a}.player-condition--blue{color:#62adff}.player-condition--purple{color:#b98cff}.player-training-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.player-training-options button{display:grid;gap:4px;min-height:72px;padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:14px;background:rgba(255,255,255,.06);color:inherit;text-align:left}.player-training-options strong{font-size:16px}.player-training-options small{font-size:11px;color:var(--text-muted,#a9b8c8)}@media(max-width:350px){.player-roster__main{grid-template-columns:24px minmax(0,1fr) 42px 36px;padding-right:54px}.player-roster__condition small{display:none}.player-training-chip{right:5px;min-width:43px;padding-inline:5px}}\n''';w(p,t)
 # Home: remove fatigue, add offer actions and school quick action.
 p='src/features/home/HomeScreen.tsx';t=r(p);t=t.replace('import type { School, SchoolReputation } from "../../domain/model/School";','import type { School, SchoolReputation } from "../../domain/model/School";\nimport { getPlayerConditionPresentation } from "../../domain/player/playerCondition";');t=t.replace('  onOpenTraining: () => void;','  onOpenSchool: () => void;\n  onAcceptPracticeOffer: () => void;\n  onDeclinePracticeOffer: () => void;\n  operationPending: boolean;');t=t.replace('  onOpenTraining,','  onOpenSchool,\n  onAcceptPracticeOffer,\n  onDeclinePracticeOffer,\n  operationPending,');t=t.replace('  const averageFatigue = average(players.map((player) => player.fatigue));\n','  const averageCondition = average(players.map((player) => player.condition));\n  const teamCondition = getPlayerConditionPresentation(averageCondition);\n');t=t.replace('  const fatigueWarningCount = players.filter(\n    (player) => player.fatigue >= 65,\n  ).length;\n','');t=t.replace('  const alertText =\n    injuredCount > 0 || fatigueWarningCount > 0\n      ? [\n          injuredCount > 0 ? `怪我 ${injuredCount}人` : null,\n          fatigueWarningCount > 0 ? `疲労注意 ${fatigueWarningCount}人` : null,\n        ]\n          .filter(Boolean)\n          .join("・")\n      : null;','  const alertText = injuredCount > 0 ? `怪我 ${injuredCount}人` : null;\n  const incomingOffer = state.weeklySchedule.practiceMatch.incomingOffer;\n  const incomingSchool = incomingOffer ? state.schools[incomingOffer.schoolId] : null;');
 old='''        <div className="home-week-card__actions" aria-label="今週の操作">\n          <button\n            aria-label="育成を決める"\n            onClick={onOpenTraining}\n            type="button"\n          >\n            育成\n          </button>\n          <button\n            aria-label="チーム編成を確認"\n            onClick={onOpenTeam}\n            type="button"\n          >\n            編成\n          </button>''';new='''        {incomingOffer && incomingSchool && !scheduledPracticeOpponentId ? (\n          <section className="home-practice-offer" aria-label="練習試合の申し込み">\n            <div><span>練習試合の申し込み</span><strong>{incomingSchool.shortName}</strong><small>成長 {incomingOffer.growthRating}/5 ・ 負荷 {incomingOffer.loadRating}/5</small></div>\n            <div><button disabled={operationPending} onClick={onDeclinePracticeOffer} type="button">断る</button><button className="is-primary" disabled={operationPending} onClick={onAcceptPracticeOffer} type="button">受ける</button></div>\n          </section>\n        ) : null}\n        <div className="home-week-card__actions" aria-label="今週の操作">\n          <button aria-label="選手を確認" onClick={onOpenTeam} type="button">選手</button>\n          <button aria-label="学校を確認" onClick={onOpenSchool} type="button">学校</button>''';
 if old not in t: raise SystemExit('home actions pattern');t=t.replace(old,new,1);t=t.replace('                      ・疲労 {signed(notification.payload.totalFatigueChange)}\n','');t=t.replace('''        <article>\n          <span>疲労</span>\n          <strong>{averageFatigue}</strong>\n          <small>\n            {fatigueWarningCount > 0 ? `注意 ${fatigueWarningCount}人` : "安定"}\n          </small>\n        </article>''','''        <article className={`player-condition--${teamCondition.colorToken}`}><span>調子</span><strong>{teamCondition.icon}</strong><small>{teamCondition.label}</small></article>''');w(p,t)
 p='src/features/home/home.css';t=r(p);t+='''\n.home-practice-offer{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:10px 0;padding:10px 12px;border:1px solid rgba(255,170,55,.38);border-radius:14px;background:linear-gradient(135deg,rgba(255,151,31,.16),rgba(24,87,139,.18))}.home-practice-offer>div:first-child{display:grid;gap:2px}.home-practice-offer span,.home-practice-offer small{font-size:11px}.home-practice-offer strong{font-size:16px}.home-practice-offer>div:last-child{display:flex;gap:6px}.home-practice-offer button{min-width:54px;padding:8px;border-radius:10px}.home-practice-offer .is-primary{background:#f59b23;color:#111827;font-weight:900}\n''';w(p,t)
 # GameApp routing/wiring.
 p='src/app/GameApp.tsx';t=r(p);t=t.replace('import { TrainingScreen } from "../features/training/TrainingScreen";\nimport { TrainingScoutingEntry } from "../features/training/TrainingScoutingEntry";\n','');t=t.replace('type MoreView = "menu" | "school" | "shop";','type MoreView = "menu" | "shop";');t=t.replace('if (tab !== "training") {','if (tab !== "school") {');
 needle='''  const saveTrainingPlan = async (plan: WeeklyPlan) => {\n    if (trainingCompleted) return;\n    await cloudSession.runAction(\n      { type: "set-training-plan", plan },\n      "練習設定を保存しています…",\n    );\n  };''';add=needle+'''\n\n  const changePlayerTraining = async (playerId: PlayerId, instructionId: string) => {\n    const current = gameState.weeklySchedule.trainingPlan;\n    await saveTrainingPlan({\n      ...current,\n      individualAssignments: [\n        ...current.individualAssignments.filter((item) => item.playerId !== playerId),\n        { playerId, instructionId },\n      ],\n    });\n  };''';
 if needle not in t: raise SystemExit('save training pattern');t=t.replace(needle,add,1)
 t=t.replace('        onOpenTeam={() => setActiveTab("team")}\n        onOpenTraining={() => setActiveTab("training")}','        onOpenTeam={() => setActiveTab("team")}\n        onOpenSchool={() => setActiveTab("school")}\n        onAcceptPracticeOffer={() => void acceptPracticeOffer()}\n        onDeclinePracticeOffer={() => void declinePracticeOffer()}\n        operationPending={cloudSession.operation.status === "submitting"}')
 t=t.replace('        onChange={saveTeamSelection}\n        selection={teamSelection}','        onChange={saveTeamSelection}\n        onChangeTraining={changePlayerTraining}\n        trainingPending={cloudSession.operation.status === "submitting"}\n        selection={teamSelection}',1)
 start=t.index('    ) : activeTab === "training" && scoutingOpen ? (');end=t.index('    ) : activeTab === "match" && officialTournamentView ? (',start)
 schoolbranch='''    ) : activeTab === "school" && scoutingOpen ? (\n      <ScoutingScreen\n        error={scoutingError}\n        latestShopUseResult={latestShopUseResult}\n        loading={scoutingLoading}\n        onBack={() => { setScoutingOpen(false); setScoutingError(null); setRetryRecruitCandidateId(null); }}\n        onRecruit={(candidateId) => { void recruitCandidate(candidateId); }}\n        onRetry={retryScouting}\n        onUseShopItem={(itemId, target) => { void consumeShopItemFromUi(itemId, target); }}\n        recruitingCandidateId={recruitingCandidateId}\n        reports={scoutingReports}\n        shopPendingCandidateId={shopPendingTarget?.type === "scouting-candidate" ? shopPendingTarget.candidateId : null}\n        shopPendingItemId={shopPendingItemId}\n        shopStatus={shopStatus}\n        state={gameState}\n      />\n    ) : activeTab === "school" ? (\n      <SchoolScreen onOpenScouting={openScouting} onUpgradeFacility={upgradeSchoolFacility} state={gameState} />\n'''
 t=t[:start]+schoolbranch+t[end:]
 old='''    ) : moreView === "school" ? (\n      <main className="app-content more-school-view">\n        <button\n          className="more-school-view__back"\n          onClick={() => setMoreView("menu")}\n          type="button"\n        >\n          その他へ戻る\n        </button>\n        <SchoolScreen\n          onUpgradeFacility={upgradeSchoolFacility}\n          state={gameState}\n        />\n      </main>\n    ) : (\n      <MoreScreen\n        accountLabel={session.email ?? "ログイン済みアカウント"}\n        onOpenSchool={() => setMoreView("school")}\n        onOpenShop={openShop}\n        onSignOut={() => void auth.signOut()}\n      />\n    );''';new='''    ) : (\n      <MoreScreen\n        accountLabel={session.email ?? "ログイン済みアカウント"}\n        onOpenShop={openShop}\n        onSignOut={() => void auth.signOut()}\n      />\n    );''';
 if old not in t: raise SystemExit('more school branch');t=t.replace(old,new,1);w(p,t)
 # Team picker wording: rotation is context, player position is prominent.
 p='src/features/team/TeamScreen.tsx';t=r(p);t=t.replace('ローテーション{selectedSlot}の選手を選択','変更する枠：ローテーション{selectedSlot}');w(p,t)

if len(sys.argv)!=2: raise SystemExit('tests|production')
(tests if sys.argv[1]=='tests' else production)()
